name: Run tests and deply
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Quality checks
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install the project
      run: npm install
  
    - name: Run lint
      run: npm run lint -- --no-fix

    - name: Run unit tests
      run: npm run test:unit:coverage
    - name: Run e2e tests
      run: npm run test:e2e

    - name: Unit tests coverage artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-unit
        path: coverage-unit/lcov-report

    - name: E2e tests coverage artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-e2e
        path: coverage-e2e-report/lcov-report    

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Create archive
      run: |
        cd dist
        zip -9 -r  dist.zip .

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: build
        FOLDER: dist/
        CLEAN: true