name: Run tests
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install the project
      run: npm install
  
    - name: Run lint
      run: npm run lint -- --no-fix

    - name: Run unit tests
      run: npm run test:unit:coverage
    - name: Run e2e tests
      run: npm run test:e2e
    - name: Merge coverage
      run: npm run coverage:final:merge
    - name: Build coverage report
      run: npm run coverage:final:report

    - name: Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage-report/lcov-report
